name: Deploy Azure Data Factory

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Data Factory
      run: |
        az datafactory create --resource-group <resource-group> --factory-name <factory-name> --location <location>
        az datafactory pipeline create --resource-group <resource-group> --factory-name <factory-name> --name <pipeline-name> --definition @pipeline.json